import type { Team, Character, Unit, Circle, QRCode, PointEntry, TablerIcon } from "./types"
import {
  IconCat, IconCrown, IconSwords, IconFlame, IconMask,
  IconBrush, IconPaw, IconUsersGroup, IconRosette, IconCpu,
} from "@tabler/icons-react"

export const TEAMS: Team[] = [
  { id:"T01", name:"Tým 1",  unitId:"U1", memberIds:["S001","S002","S003"], points:145, color:"#e05252" },
  { id:"T02", name:"Tým 2",  unitId:"U1", memberIds:["S004","S005","S006"], points:130, color:"#e09832" },
  { id:"T03", name:"Tým 3",  unitId:"U2", memberIds:["S007","S008","S009"], points:160, color:"#5268e0" },
  { id:"T04", name:"Tým 4",  unitId:"U2", memberIds:["S010","S011","S012"], points: 90, color:"#52b0e0" },
  { id:"T05", name:"Tým 5",  unitId:"U5", memberIds:["S013","S014","S015"], points:120, color:"#52d4b4" },
  { id:"T06", name:"Tým 6",  unitId:"U5", memberIds:["S016","S017","S018"], points:175, color:"#d4a017" },
  { id:"T07", name:"Tým 7",  unitId:"U3", memberIds:["S019","S020","S021"], points:110, color:"#a052e0" },
  { id:"T08", name:"Tým 8",  unitId:"U3", memberIds:["S022","S023","S024"], points:100, color:"#52c452" },
  { id:"T09", name:"Tým 9",  unitId:"U4", memberIds:["S025","S026","S027"], points:155, color:"#e052b4" },
  { id:"T10", name:"Tým 10", unitId:"U4", memberIds:["S028","S029","S030"], points:140, color:"#e0cc52" },
]

export const TEAM_ICONS: Record<string, TablerIcon> = {
  T01: IconCat,
  T02: IconCrown,
  T03: IconSwords,
  T04: IconFlame,
  T05: IconMask,
  T06: IconBrush,
  T07: IconPaw,
  T08: IconUsersGroup,
  T09: IconRosette,
  T10: IconCpu,
}

export const UNITS: Unit[] = [
  { id:"U1", name:"Murakami", teamIds:["T01","T02"] },
  { id:"U2", name:"Hagakure", teamIds:["T03","T04"] },
  { id:"U3", name:"Hvězdy",   teamIds:["T07","T08"] },
  { id:"U4", name:"V.I.R.A.", teamIds:["T09","T10"] },
  { id:"U5", name:"Utsuro",   teamIds:["T05","T06"] },
]

export const CIRCLES: Circle[] = [
  { id:"C1", name:"Kuchi-Kuchi",     memberIds:["S003","S009","S015","S021","S026"] },
  { id:"C2", name:"Kaligrafie",      memberIds:["S016","S017","S018","S006","S012"] },
  { id:"C3", name:"Vědecký",         memberIds:["S030","S002","S008","S011","S020"] },
  { id:"C4", name:"Rituální",        memberIds:["S023","S001","S010","S019","S024"] },
  { id:"C5", name:"Akano Shōko-dan", memberIds:["S025","S026","S027","S004","S013"] },
  { id:"C6", name:"Literární",       memberIds:["S007","S014","S022","S028","S029"] },
]

export const CHARACTERS: Character[] = [
  // ── GM ──
  { id:"GM1",  code:"GM-001",   name:"GM",        role:"gm",
    circleIds:[], kaichiLevel:0, points:0, peerPointPool:0, lessonClaimedThisWindow:false },
  // ── Učitelé ──
  { id:"TCH6", code:"TCH-006",  name:"Arakami",   role:"teacher",
    circleIds:[], kaichiLevel:6, points:0, peerPointPool:0, lessonClaimedThisWindow:false },
  { id:"TCH1", code:"TCH-001",  name:"Shiranagi", role:"teacher",
    circleIds:[], kaichiLevel:5, points:0, peerPointPool:0, lessonClaimedThisWindow:false },
  { id:"TCH2", code:"TCH-002",  name:"Nakamura",  role:"teacher",
    circleIds:[], kaichiLevel:7, points:0, peerPointPool:0, lessonClaimedThisWindow:false },
  { id:"TCH3", code:"TCH-003",  name:"Ibuki",     role:"teacher",
    circleIds:[], kaichiLevel:5, points:0, peerPointPool:0, lessonClaimedThisWindow:false },
  { id:"TCH4", code:"TCH-004",  name:"Karasu",    role:"teacher",
    circleIds:[], kaichiLevel:6, points:0, peerPointPool:0, lessonClaimedThisWindow:false },
  { id:"TCH5", code:"TCH-005",  name:"Okuda",     role:"teacher",
    circleIds:[], kaichiLevel:6, points:0, peerPointPool:0, lessonClaimedThisWindow:false },
  // ── Obrazovky ──
  { id:"DSP1", code:"SCREEN-A", name:"Obrazovka A", role:"display",
    circleIds:[], kaichiLevel:0, points:0, peerPointPool:0, lessonClaimedThisWindow:false },
  { id:"DSP2", code:"SCREEN-B", name:"Obrazovka B", role:"display",
    circleIds:[], kaichiLevel:0, points:0, peerPointPool:0, lessonClaimedThisWindow:false },
  // ── Knihovna ──
  { id:"LIB1", code:"KNIHOVNA", name:"Knihovna", role:"library",
    circleIds:[], kaichiLevel:0, points:0, peerPointPool:0, lessonClaimedThisWindow:false },
  // ── Tým 1 ──
  { id:"S001", code:"STU-001", name:"Mushashi", nickname:"Drsňák",      role:"student",
    teamId:"T01", unitId:"U1", circleIds:["C4"], specialization:"combat",
    kaichiLevel:4, points:52, peerPointPool:18, lessonClaimedThisWindow:false },
  { id:"S002", code:"STU-002", name:"Shigen",   nickname:"Zmatený",     role:"student",
    teamId:"T01", unitId:"U1", circleIds:["C3"], specialization:"tactical",
    kaichiLevel:3, points:48, peerPointPool:20, lessonClaimedThisWindow:false },
  { id:"S003", code:"STU-003", name:"Mimi",     nickname:"Pečovatelka", role:"student",
    teamId:"T01", unitId:"U1", circleIds:["C1"], specialization:"support",
    kaichiLevel:3, points:45, peerPointPool:20, lessonClaimedThisWindow:false },
  // ── Tým 2 ──
  { id:"S004", code:"STU-004", name:"Kaya",  nickname:"Princezna",   role:"student",
    teamId:"T02", unitId:"U1", circleIds:["C5"], specialization:"tactical",
    kaichiLevel:3, points:44, peerPointPool:17, lessonClaimedThisWindow:false },
  { id:"S005", code:"STU-005", name:"Kaoru", nickname:"Kluk ze vsi", role:"student",
    teamId:"T02", unitId:"U1", circleIds:["C6"], specialization:"support",
    kaichiLevel:2, points:42, peerPointPool:20, lessonClaimedThisWindow:false },
  { id:"S006", code:"STU-006", name:"Hiko",  nickname:"Služebník",   role:"student",
    teamId:"T02", unitId:"U1", circleIds:["C2"], specialization:"tactical",
    kaichiLevel:2, points:44, peerPointPool:20, lessonClaimedThisWindow:false },
  // ── Tým 3 ──
  { id:"S007", code:"STU-007", name:"Ikai",  nickname:"Vůdkyně",             role:"student",
    teamId:"T03", unitId:"U2", circleIds:["C6"], specialization:"tactical",
    kaichiLevel:4, points:56, peerPointPool:12, lessonClaimedThisWindow:false },
  { id:"S008", code:"STU-008", name:"Raiji", nickname:"Zavázaný povinností", role:"student",
    teamId:"T03", unitId:"U2", circleIds:["C3"], specialization:"combat",
    kaichiLevel:4, points:54, peerPointPool:15, lessonClaimedThisWindow:false },
  { id:"S009", code:"STU-009", name:"Airi",  nickname:"Ztracená",            role:"student",
    teamId:"T03", unitId:"U2", circleIds:["C1"], specialization:"support",
    kaichiLevel:4, points:50, peerPointPool:20, lessonClaimedThisWindow:false },
  // ── Tým 4 ──
  { id:"S010", code:"STU-010", name:"Yuri", nickname:"Hledačka pravdy", role:"student",
    teamId:"T04", unitId:"U2", circleIds:["C4"], specialization:"tactical",
    kaichiLevel:2, points:30, peerPointPool:20, lessonClaimedThisWindow:false },
  { id:"S011", code:"STU-011", name:"Saya", nickname:"Ta Pečlivá",      role:"student",
    teamId:"T04", unitId:"U2", circleIds:["C3"], specialization:"support",
    kaichiLevel:2, points:30, peerPointPool:20, lessonClaimedThisWindow:false },
  { id:"S012", code:"STU-012", name:"Ren",  nickname:"Nezlomný",        role:"student",
    teamId:"T04", unitId:"U2", circleIds:["C2"], specialization:"tactical",
    kaichiLevel:2, points:30, peerPointPool:20, lessonClaimedThisWindow:false },
  // ── Tým 5 ──
  { id:"S013", code:"STU-013", name:"Tetsuya", nickname:"Zklamaný",  role:"student",
    teamId:"T05", unitId:"U5", circleIds:["C5"], specialization:"combat",
    kaichiLevel:3, points:42, peerPointPool:18, lessonClaimedThisWindow:false },
  { id:"S014", code:"STU-014", name:"Itsuki",  nickname:"Ten druhý", role:"student",
    teamId:"T05", unitId:"U5", circleIds:["C6"], specialization:"support",
    kaichiLevel:2, points:39, peerPointPool:20, lessonClaimedThisWindow:false },
  { id:"S015", code:"STU-015", name:"Akari",   nickname:"Osamělá",   role:"student",
    teamId:"T05", unitId:"U5", circleIds:["C1"], specialization:"tactical",
    kaichiLevel:3, points:39, peerPointPool:20, lessonClaimedThisWindow:false },
  // ── Tým 6 ──
  { id:"S016", code:"STU-016", name:"Ayumi",   nickname:"Pátrající",      role:"student",
    teamId:"T06", unitId:"U5", circleIds:["C2"], specialization:"tactical",
    kaichiLevel:4, points:58, peerPointPool:15, lessonClaimedThisWindow:false },
  { id:"S017", code:"STU-017", name:"Mizuki",  nickname:"Průměrný",       role:"student",
    teamId:"T06", unitId:"U5", circleIds:["C2"], specialization:"tactical",
    kaichiLevel:2, points:55, peerPointPool:20, lessonClaimedThisWindow:false },
  { id:"S018", code:"STU-018", name:"Yoshika", nickname:"Chlouba rodiny", role:"student",
    teamId:"T06", unitId:"U5", circleIds:["C2"], specialization:"combat",
    kaichiLevel:3, points:62, peerPointPool:18, lessonClaimedThisWindow:false },
  // ── Tým 7 ──
  { id:"S019", code:"STU-019", name:"Shiho",  nickname:"Kapitánka", role:"student",
    teamId:"T07", unitId:"U3", circleIds:["C4"], specialization:"combat",
    kaichiLevel:4, points:36, peerPointPool:14, lessonClaimedThisWindow:false },
  { id:"S020", code:"STU-020", name:"Yusuke", nickname:"Bídák",     role:"student",
    teamId:"T07", unitId:"U3", circleIds:["C3"], specialization:"tactical",
    kaichiLevel:2, points:37, peerPointPool:20, lessonClaimedThisWindow:false },
  { id:"S021", code:"STU-021", name:"Anna",   nickname:"Cizačka",   role:"student",
    teamId:"T07", unitId:"U3", circleIds:["C1"], specialization:"support",
    kaichiLevel:3, points:37, peerPointPool:20, lessonClaimedThisWindow:false },
  // ── Tým 8 ──
  { id:"S022", code:"STU-022", name:"Kei",    nickname:"Dědic",    role:"student",
    teamId:"T08", unitId:"U3", circleIds:["C6"], specialization:"combat",
    kaichiLevel:3, points:33, peerPointPool:18, lessonClaimedThisWindow:false },
  { id:"S023", code:"STU-023", name:"Ryo",    nickname:"Oblíbený", role:"student",
    teamId:"T08", unitId:"U3", circleIds:["C4"], specialization:"support",
    kaichiLevel:2, points:34, peerPointPool:20, lessonClaimedThisWindow:false },
  { id:"S024", code:"STU-024", name:"Haruka", nickname:"Chudinka", role:"student",
    teamId:"T08", unitId:"U3", circleIds:["C4"], specialization:"support",
    kaichiLevel:2, points:33, peerPointPool:20, lessonClaimedThisWindow:false },
  // ── Tým 9 ──
  { id:"S025", code:"STU-025", name:"Tomoe",   nickname:"Princ",  role:"student",
    teamId:"T09", unitId:"U4", circleIds:["C5"], specialization:"tactical",
    kaichiLevel:3, points:52, peerPointPool:18, lessonClaimedThisWindow:false },
  { id:"S026", code:"RUZE-001", name:"Nozomi", nickname:"Růže",   role:"ruze",
    teamId:"T09", unitId:"U4", circleIds:["C1","C5"], specialization:"support",
    kaichiLevel:4, points:53, peerPointPool:12, lessonClaimedThisWindow:false },
  { id:"S027", code:"STU-027", name:"Sestsuko", nickname:"Kometa", role:"student",
    teamId:"T09", unitId:"U4", circleIds:["C5"], specialization:"combat",
    kaichiLevel:3, points:50, peerPointPool:18, lessonClaimedThisWindow:false },
  // ── Tým 10 ──
  { id:"S028", code:"STU-028", name:"Kenzo",   nickname:"Oheň",   role:"student",
    teamId:"T10", unitId:"U4", circleIds:["C6"], specialization:"tactical",
    kaichiLevel:3, points:46, peerPointPool:18, lessonClaimedThisWindow:false },
  { id:"S029", code:"STU-029", name:"Makoto",  nickname:"Voda",   role:"student",
    teamId:"T10", unitId:"U4", circleIds:["C6"], specialization:"combat",
    kaichiLevel:4, points:47, peerPointPool:15, lessonClaimedThisWindow:false },
  { id:"S030", code:"STU-030", name:"Chiharu", nickname:"Vzduch", role:"student",
    teamId:"T10", unitId:"U4", circleIds:["C3"], specialization:"support",
    kaichiLevel:2, points:47, peerPointPool:20, lessonClaimedThisWindow:false },
]

// ─── Point log (seeded 2-day history) ────────────────────────────────────────
const BASE_TIME = new Date("2026-04-22T09:00:00")
function t(offsetMin: number) { return new Date(BASE_TIME.getTime() + offsetMin * 60000) }

export const INITIAL_POINT_LOG: PointEntry[] = [
  { id:"PE01", timestamp:t(10),  sourceRole:"teacher", sourceCharacterId:"TCH1", targetType:"team",   targetId:"T06", resolvedTeamIds:["T06"], amount:20, actionType:"mission_success", note:"Průzkum západního křídla" },
  { id:"PE02", timestamp:t(25),  sourceRole:"teacher", sourceCharacterId:"TCH2", targetType:"unit",   targetId:"U2",  resolvedTeamIds:["T03","T04"], amount:15, actionType:"lesson", note:"Hodina historie" },
  { id:"PE03", timestamp:t(40),  sourceRole:"gm",      sourceCharacterId:"GM1",  targetType:"team",   targetId:"T01", resolvedTeamIds:["T01"], amount:25, actionType:"mission_success", note:"Mise alfa dokončena" },
  { id:"PE04", timestamp:t(55),  sourceRole:"teacher", sourceCharacterId:"TCH1", targetType:"team",   targetId:"T09", resolvedTeamIds:["T09"], amount:20, actionType:"monster", note:"Stráž poraženar" },
  { id:"PE05", timestamp:t(70),  sourceRole:"gm",      sourceCharacterId:"GM1",  targetType:"team",   targetId:"T03", resolvedTeamIds:["T03"], amount:30, actionType:"mission_success", note:"Špionáž úspěšná" },
  { id:"PE06", timestamp:t(90),  sourceRole:"ruze",    sourceCharacterId:"RUZ1", targetType:"circle", targetId:"C6",  resolvedTeamIds:["T01","T03","T04"], amount:10, actionType:"simulation", note:"Bojový turnaj" },
  { id:"PE07", timestamp:t(110), sourceRole:"teacher", sourceCharacterId:"TCH2", targetType:"unit",   targetId:"U4",  resolvedTeamIds:["T07","T08"], amount:15, actionType:"lesson" },
  { id:"PE08", timestamp:t(130), sourceRole:"gm",      sourceCharacterId:"GM1",  targetType:"team",   targetId:"T06", resolvedTeamIds:["T06"], amount:20, actionType:"shidosei" },
  { id:"PE09", timestamp:t(150), sourceRole:"teacher", sourceCharacterId:"TCH1", targetType:"team",   targetId:"T02", resolvedTeamIds:["T02"], amount:-10, actionType:"correction", note:"Oprava — duplikát" },
  { id:"PE10", timestamp:t(170), sourceRole:"teacher", sourceCharacterId:"TCH2", targetType:"team",   targetId:"T05", resolvedTeamIds:["T05"], amount:20, actionType:"mission_success" },
  { id:"PE11", timestamp:t(200), sourceRole:"gm",      sourceCharacterId:"GM1",  targetType:"unit",   targetId:"U3",  resolvedTeamIds:["T05","T06"], amount:25, actionType:"mission_success", note:"Mise Omega splněna" },
  { id:"PE12", timestamp:t(230), sourceRole:"ruze",    sourceCharacterId:"RUZ1", targetType:"team",   targetId:"T07", resolvedTeamIds:["T07"], amount:15, actionType:"informant" },
  { id:"PE13", timestamp:t(260), sourceRole:"teacher", sourceCharacterId:"TCH1", targetType:"unit",   targetId:"U1",  resolvedTeamIds:["T01","T02"], amount:15, actionType:"lesson" },
  { id:"PE14", timestamp:t(300), sourceRole:"gm",      sourceCharacterId:"GM1",  targetType:"team",   targetId:"T09", resolvedTeamIds:["T09"], amount:20, actionType:"qr_quest" },
  { id:"PE15", timestamp:t(340), sourceRole:"teacher", sourceCharacterId:"TCH2", targetType:"circle", targetId:"C1",  resolvedTeamIds:["T01","T02","T04"], amount:10, actionType:"simulation", note:"Sportovní kruh — turnaj" },
  { id:"PE16", timestamp:t(380), sourceRole:"gm",      sourceCharacterId:"GM1",  targetType:"team",   targetId:"T10", resolvedTeamIds:["T10"], amount:30, actionType:"mission_success" },
  { id:"PE17", timestamp:t(420), sourceRole:"teacher", sourceCharacterId:"TCH1", targetType:"team",   targetId:"T03", resolvedTeamIds:["T03"], amount:15, actionType:"lesson" },
  { id:"PE18", timestamp:t(460), sourceRole:"ruze",    sourceCharacterId:"RUZ1", targetType:"unit",   targetId:"U5",  resolvedTeamIds:["T09","T10"], amount:20, actionType:"mission_success", note:"Noc infiltrátorů" },
  { id:"PE19", timestamp:t(500), sourceRole:"gm",      sourceCharacterId:"GM1",  targetType:"team",   targetId:"T04", resolvedTeamIds:["T04"], amount:10, actionType:"shidosei" },
  { id:"PE20", timestamp:t(540), sourceRole:"teacher", sourceCharacterId:"TCH2", targetType:"unit",   targetId:"U2",  resolvedTeamIds:["T03","T04"], amount:15, actionType:"lesson" },
  // Day 2
  { id:"PE21", timestamp:t(780),  sourceRole:"gm",      sourceCharacterId:"GM1",  targetType:"team",   targetId:"T06", resolvedTeamIds:["T06"], amount:25, actionType:"mission_success", note:"Ráno druhého dne" },
  { id:"PE22", timestamp:t(820),  sourceRole:"teacher", sourceCharacterId:"TCH1", targetType:"circle", targetId:"C2",  resolvedTeamIds:["T01","T03","T05"], amount:10, actionType:"simulation" },
  { id:"PE23", timestamp:t(860),  sourceRole:"ruze",    sourceCharacterId:"RUZ1", targetType:"team",   targetId:"T08", resolvedTeamIds:["T08"], amount:20, actionType:"monster" },
  { id:"PE24", timestamp:t(900),  sourceRole:"gm",      sourceCharacterId:"GM1",  targetType:"unit",   targetId:"U3",  resolvedTeamIds:["T05","T06"], amount:15, actionType:"lesson" },
  { id:"PE25", timestamp:t(940),  sourceRole:"teacher", sourceCharacterId:"TCH2", targetType:"team",   targetId:"T09", resolvedTeamIds:["T09"], amount:20, actionType:"qr_quest", note:"QR kód — sklep" },
  { id:"PE26", timestamp:t(980),  sourceRole:"gm",      sourceCharacterId:"GM1",  targetType:"team",   targetId:"T02", resolvedTeamIds:["T02"], amount:30, actionType:"mission_success" },
  { id:"PE27", timestamp:t(1020), sourceRole:"teacher", sourceCharacterId:"TCH1", targetType:"unit",   targetId:"U4",  resolvedTeamIds:["T07","T08"], amount:15, actionType:"mission_success" },
  { id:"PE28", timestamp:t(1060), sourceRole:"ruze",    sourceCharacterId:"RUZ1", targetType:"team",   targetId:"T01", resolvedTeamIds:["T01"], amount:20, actionType:"shidosei" },
  { id:"PE29", timestamp:t(1100), sourceRole:"gm",      sourceCharacterId:"GM1",  targetType:"team",   targetId:"T07", resolvedTeamIds:["T07"], amount:15, actionType:"informant" },
  { id:"PE30", timestamp:t(1140), sourceRole:"teacher", sourceCharacterId:"TCH2", targetType:"circle", targetId:"C6",  resolvedTeamIds:["T01","T03","T04"], amount:15, actionType:"simulation", note:"Bojový kruh — výsledky" },
]

export const INITIAL_QR_CODES: QRCode[] = [
  { id:"QR01", token:"akn-abc123", label:"Sklep — průzkum", targetType:"team", targetId:"T09",
    points:20, validity:"once", timesScanned:1, status:"used", createdAt:t(880) },
  { id:"QR02", token:"akn-def456", label:"Věžní místnost", targetType:"unit", targetId:"U2",
    points:15, validity:"timed", validUntil:new Date("2026-04-23T20:00:00"), timesScanned:0, status:"active", createdAt:t(950) },
  { id:"QR03", token:"akn-ghi789", label:"Chodba — tajná zpráva", targetType:"circle", targetId:"C3",
    points:10, validity:"repeat", timesScanned:3, status:"active", createdAt:t(800) },
]
